### ISSUE TITLE
3.4.0 Soon ? PropTypes fix is critical for RN > 0.44.0

### ISSUE THREAD

**Issue by VinceBT** [oblador/react-native-progress#73]
Everything is in the title

**Comment by mmmurf** [comment]
It appears that PropTypes in the following line is being scoped to mean React.PropTypes

https://github.com/oblador/react-native-progress/blob/master/Circle.js#L31

The new 'prop-types' library is being used, but due to the above issue it is being ignored.

https://github.com/oblador/react-native-progress/blob/master/Circle.js#L2

**Comment by mmmurf** [comment]
I submitted a pull request which fixes the issue: 

https://github.com/oblador/react-native-progress/pull/75

**Comment by oblador** [comment]
[3.4.0](https://github.com/oblador/react-native-progress/releases/tag/v3.4.0) is out!
